/*
時間：1, 3, 7, 14, 28, 60
國家：TW, FN
幣別：TWD, FCD
特徵：總金額、總次數；與上一周期金額差、與上一周期次數差；與上一周期金額差比例、與上一周期次數差比例；

共 6*2*2*6 = 144個
*/


DEFINE DATE1 = 1
;

SELECT CUST_ID
--總金額&總次數
--1
, SUM(CASE WHEN DATEKEY = &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_1D
, COUNT(CASE WHEN DATEKEY = &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_1D
, SUM(CASE WHEN DATEKEY = &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_1D
, COUNT(CASE WHEN DATEKEY = &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_1D
, SUM(CASE WHEN DATEKEY = &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_1D
, COUNT(CASE WHEN DATEKEY = &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_1D
, SUM(CASE WHEN DATEKEY = &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_1D
, COUNT(CASE WHEN DATEKEY = &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_1D

--3
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_3D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_3D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_3D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_3D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_3D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_3D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_3D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_3D

--7
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_7D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_7D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_7D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_7D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_7D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_7D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_7D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_7D
    
--14
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_14D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_14D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_14D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_14D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_14D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_14D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_14D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_14D
  
--28
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_28D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_28D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_28D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_28D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_28D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_28D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_28D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_28D

--60
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_60D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_60D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_60D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_60D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_60D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_60D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_60D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_60D

---------------------------------------------------------------------------------------------------------------------------------------
--金額差&次數差
--1
, SUM(CASE WHEN DATEKEY = &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = &DATE1-1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_1D
, COUNT(CASE WHEN DATEKEY = &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY = &DATE1-1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_DIFF_1D
, SUM(CASE WHEN DATEKEY = &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = &DATE1-1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_1D
, COUNT(CASE WHEN DATEKEY = &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY = &DATE1-1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_DIFF_1D
, SUM(CASE WHEN DATEKEY = &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = &DATE1-1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_1D
, COUNT(CASE WHEN DATEKEY = &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) -COUNT(CASE WHEN DATEKEY = &DATE1-1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_DIFF_1D
, SUM(CASE WHEN DATEKEY = &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = &DATE1-1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_1D
, COUNT(CASE WHEN DATEKEY = &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY = &DATE1-1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_DIFF_1D

--3
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-5 AND &DATE1-3 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_3D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-5 AND &DATE1-3 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_DIFF_3D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-5 AND &DATE1-3 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_3D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-5 AND &DATE1-3 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_DIFF_3D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-5 AND &DATE1-3 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_3D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-5 AND &DATE1-3 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_DIFF_3D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) -SUM(CASE WHEN DATEKEY BETWEEN &DATE1-5 AND &DATE1-3 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_3D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-5 AND &DATE1-3 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_DIFF_3D

--7
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1-7 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_7D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1-7 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_DIFF_7D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1-7 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_7D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1-7 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_DIFF_7D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1-7 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_7D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1-7 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_DIFF_7D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1-7 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_7D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1-7 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_DIFF_7D
    
--14
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1-14 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_14D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1-14 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_DIFF_14D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1-14 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_14D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1-14 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_DIFF_14D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1-14 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_14D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1-14 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_DIFF_14D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1-14 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_14D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1-14 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_DIFF_14D
  
--28
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-55 AND &DATE1-28 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_28D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-55 AND &DATE1-28 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_DIFF_28D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-55 AND &DATE1-28 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_28D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-55 AND &DATE1-28 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_DIFF_28D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-55 AND &DATE1-28 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_28D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-55 AND &DATE1-28 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_DIFF_28D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-55 AND &DATE1-28 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_28D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-55 AND &DATE1-28 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_DIFF_28D

--60
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-119 AND &DATE1-60 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_60D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-119 AND &DATE1-60 AND COUNTRY = 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) TW_TWD_CNT_DIFF_60D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-119 AND &DATE1-60 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_60D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-119 AND &DATE1-60 AND COUNTRY = 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) TW_FCD_CNT_DIFF_60D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-119 AND &DATE1-60 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_60D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-119 AND &DATE1-60 AND COUNTRY != 130 AND cur_type = 47 THEN CUST_ID ELSE NULL END) FN_TWD_CNT_DIFF_60D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN &DATE1-119 AND &DATE1-60 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_60D
, COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN &DATE1-119 AND &DATE1-60 AND COUNTRY != 130 AND cur_type != 47 THEN CUST_ID ELSE NULL END) FN_FCD_CNT_DIFF_60D

FROM CDTX
GROUP BY CUST_ID

--金額差比例&次數差比例 待補
