drop table CDTX_FEATURES PURGE;

CREATE TABLE CDTX_FEATURES
   (	
    CUST_ID VARCHAR2(200 BYTE)
    , DATEKEY NUMBER
    , ALL_AMT NUMBER
    , ALL_CNT NUMBER
    , ALL_DAY NUMBER
    , MAX_AMT NUMBER
    , TW_TWD_AMT_1D NUMBER
    , TW_TWD_CNT_1D NUMBER
    , TW_FCD_AMT_1D NUMBER
    , TW_FCD_CNT_1D NUMBER
    , FN_TWD_AMT_1D NUMBER
    , FN_TWD_CNT_1D NUMBER
    , FN_FCD_AMT_1D NUMBER
    , FN_FCD_CNT_1D NUMBER
    , TW_TWD_AMT_3D NUMBER
    , TW_TWD_CNT_3D NUMBER
    , TW_TWD_DAY_3D NUMBER
    , TW_FCD_AMT_3D NUMBER
    , TW_FCD_CNT_3D NUMBER
    , TW_FCD_DAY_3D NUMBER
    , FN_TWD_AMT_3D NUMBER
    , FN_TWD_CNT_3D NUMBER
    , FN_TWD_DAY_3D NUMBER
    , FN_FCD_AMT_3D NUMBER
    , FN_FCD_CNT_3D NUMBER
    , FN_FCD_DAY_3D NUMBER
    , TW_TWD_AMT_7D NUMBER
    , TW_TWD_CNT_7D NUMBER
    , TW_TWD_DAY_7D NUMBER
    , TW_FCD_AMT_7D NUMBER
    , TW_FCD_CNT_7D NUMBER
    , TW_FCD_DAY_7D NUMBER
    , FN_TWD_AMT_7D NUMBER
    , FN_TWD_CNT_7D NUMBER
    , FN_TWD_DAY_7D NUMBER
    , FN_FCD_AMT_7D NUMBER
    , FN_FCD_CNT_7D NUMBER
    , FN_FCD_DAY_7D NUMBER
    , TW_TWD_AMT_14D NUMBER
    , TW_TWD_CNT_14D NUMBER
    , TW_TWD_DAY_14D NUMBER
    , TW_FCD_AMT_14D NUMBER
    , TW_FCD_CNT_14D NUMBER
    , TW_FCD_DAY_14D NUMBER
    , FN_TWD_AMT_14D NUMBER
    , FN_TWD_CNT_14D NUMBER
    , FN_TWD_DAY_14D NUMBER
    , FN_FCD_AMT_14D NUMBER
    , FN_FCD_CNT_14D NUMBER
    , FN_FCD_DAY_14D NUMBER
    , TW_TWD_AMT_28D NUMBER
    , TW_TWD_CNT_28D NUMBER
    , TW_TWD_DAY_28D NUMBER
    , TW_FCD_AMT_28D NUMBER
    , TW_FCD_CNT_28D NUMBER
    , TW_FCD_DAY_28D NUMBER
    , FN_TWD_AMT_28D NUMBER
    , FN_TWD_CNT_28D NUMBER
    , FN_TWD_DAY_28D NUMBER
    , FN_FCD_AMT_28D NUMBER
    , FN_FCD_CNT_28D NUMBER
    , FN_FCD_DAY_28D NUMBER
    , TW_TWD_AMT_60D NUMBER
    , TW_TWD_CNT_60D NUMBER
    , TW_TWD_DAY_60D NUMBER
    , TW_FCD_AMT_60D NUMBER
    , TW_FCD_CNT_60D NUMBER
    , TW_FCD_DAY_60D NUMBER
    , FN_TWD_AMT_60D NUMBER
    , FN_TWD_CNT_60D NUMBER
    , FN_TWD_DAY_60D NUMBER
    , FN_FCD_AMT_60D NUMBER
    , FN_FCD_CNT_60D NUMBER
    , FN_FCD_DAY_60D NUMBER
    , TW_TWD_AMT_DIFF_1D NUMBER
    , TW_TWD_CNT_DIFF_1D NUMBER
    , TW_TWD_DAY_DIFF_1D NUMBER
    , TW_FCD_AMT_DIFF_1D NUMBER
    , TW_FCD_CNT_DIFF_1D NUMBER
    , TW_FCD_DAY_DIFF_1D NUMBER
    , FN_TWD_AMT_DIFF_1D NUMBER
    , FN_TWD_CNT_DIFF_1D NUMBER
    , FN_TWD_DAY_DIFF_1D NUMBER
    , FN_FCD_AMT_DIFF_1D NUMBER
    , FN_FCD_CNT_DIFF_1D NUMBER
    , FN_FCD_DAY_DIFF_1D NUMBER
    , TW_TWD_AMT_DIFF_3D NUMBER
    , TW_TWD_CNT_DIFF_3D NUMBER
    , TW_TWD_DAY_DIFF_3D NUMBER
    , TW_FCD_AMT_DIFF_3D NUMBER
    , TW_FCD_CNT_DIFF_3D NUMBER
    , TW_FCD_DAY_DIFF_3D NUMBER
    , FN_TWD_AMT_DIFF_3D NUMBER
    , FN_TWD_CNT_DIFF_3D NUMBER
    , FN_TWD_DAY_DIFF_3D NUMBER
    , FN_FCD_AMT_DIFF_3D NUMBER
    , FN_FCD_CNT_DIFF_3D NUMBER
    , FN_FCD_DAY_DIFF_3D NUMBER
    , TW_TWD_AMT_DIFF_7D NUMBER
    , TW_TWD_CNT_DIFF_7D NUMBER
    , TW_TWD_DAY_DIFF_7D NUMBER
    , TW_FCD_AMT_DIFF_7D NUMBER
    , TW_FCD_CNT_DIFF_7D NUMBER
    , TW_FCD_DAY_DIFF_7D NUMBER
    , FN_TWD_AMT_DIFF_7D NUMBER
    , FN_TWD_CNT_DIFF_7D NUMBER
    , FN_TWD_DAY_DIFF_7D NUMBER
    , FN_FCD_AMT_DIFF_7D NUMBER
    , FN_FCD_CNT_DIFF_7D NUMBER
    , FN_FCD_DAY_DIFF_7D NUMBER
    , TW_TWD_AMT_DIFF_14D NUMBER
    , TW_TWD_CNT_DIFF_14D NUMBER
    , TW_TWD_DAY_DIFF_14D NUMBER
    , TW_FCD_AMT_DIFF_14D NUMBER
    , TW_FCD_CNT_DIFF_14D NUMBER
    , TW_FCD_DAY_DIFF_14D NUMBER
    , FN_TWD_AMT_DIFF_14D NUMBER
    , FN_TWD_CNT_DIFF_14D NUMBER
    , FN_TWD_DAY_DIFF_14D NUMBER
    , FN_FCD_AMT_DIFF_14D NUMBER
    , FN_FCD_CNT_DIFF_14D NUMBER
    , FN_FCD_DAY_DIFF_14D NUMBER
    , TW_TWD_AMT_DIFF_28D NUMBER
    , TW_TWD_CNT_DIFF_28D NUMBER
    , TW_TWD_DAY_DIFF_28D NUMBER
    , TW_FCD_AMT_DIFF_28D NUMBER
    , TW_FCD_CNT_DIFF_28D NUMBER
    , TW_FCD_DAY_DIFF_28D NUMBER
    , FN_TWD_AMT_DIFF_28D NUMBER
    , FN_TWD_CNT_DIFF_28D NUMBER
    , FN_TWD_DAY_DIFF_28D NUMBER
    , FN_FCD_AMT_DIFF_28D NUMBER
    , FN_FCD_CNT_DIFF_28D NUMBER
    , FN_FCD_DAY_DIFF_28D NUMBER
    , TW_TWD_AMT_DIFF_60D NUMBER
    , TW_TWD_CNT_DIFF_60D NUMBER
    , TW_TWD_DAY_DIFF_60D NUMBER
    , TW_FCD_AMT_DIFF_60D NUMBER
    , TW_FCD_CNT_DIFF_60D NUMBER
    , TW_FCD_DAY_DIFF_60D NUMBER
    , FN_TWD_AMT_DIFF_60D NUMBER
    , FN_TWD_CNT_DIFF_60D NUMBER
    , FN_TWD_DAY_DIFF_60D NUMBER
    , FN_FCD_AMT_DIFF_60D NUMBER
    , FN_FCD_CNT_DIFF_60D NUMBER
    , FN_FCD_DAY_DIFF_60D NUMBER
    , TW_TWD_AMT_DIFF_PER_1D NUMBER
    , TW_TWD_CNT_DIFF_PER_1D NUMBER
    , TW_TWD_DAY_DIFF_PER_1D NUMBER
    , TW_FCD_AMT_DIFF_PER_1D NUMBER
    , TW_FCD_CNT_DIFF_PER_1D NUMBER
    , TW_FCD_DAY_DIFF_PER_1D NUMBER
    , FN_TWD_AMT_DIFF_PER_1D NUMBER
    , FN_TWD_CNT_DIFF_PER_1D NUMBER
    , FN_TWD_DAY_DIFF_PER_1D NUMBER
    , FN_FCD_AMT_DIFF_PER_1D NUMBER
    , FN_FCD_CNT_DIFF_PER_1D NUMBER
    , FN_FCD_DAY_DIFF_PER_1D NUMBER
    , TW_TWD_AMT_DIFF_PER_3D NUMBER
    , TW_TWD_CNT_DIFF_PER_3D NUMBER
    , TW_TWD_DAY_DIFF_PER_3D NUMBER
    , TW_FCD_AMT_DIFF_PER_3D NUMBER
    , TW_FCD_CNT_DIFF_PER_3D NUMBER
    , TW_FCD_DAY_DIFF_PER_3D NUMBER
    , FN_TWD_AMT_DIFF_PER_3D NUMBER
    , FN_TWD_CNT_DIFF_PER_3D NUMBER
    , FN_TWD_DAY_DIFF_PER_3D NUMBER
    , FN_FCD_AMT_DIFF_PER_3D NUMBER
    , FN_FCD_CNT_DIFF_PER_3D NUMBER
    , FN_FCD_DAY_DIFF_PER_3D NUMBER
    , TW_TWD_AMT_DIFF_PER_7D NUMBER
    , TW_TWD_CNT_DIFF_PER_7D NUMBER
    , TW_TWD_DAY_DIFF_PER_7D NUMBER
    , TW_FCD_AMT_DIFF_PER_7D NUMBER
    , TW_FCD_CNT_DIFF_PER_7D NUMBER
    , TW_FCD_DAY_DIFF_PER_7D NUMBER
    , FN_TWD_AMT_DIFF_PER_7D NUMBER
    , FN_TWD_CNT_DIFF_PER_7D NUMBER
    , FN_TWD_DAY_DIFF_PER_7D NUMBER
    , FN_FCD_AMT_DIFF_PER_7D NUMBER
    , FN_FCD_CNT_DIFF_PER_7D NUMBER
    , FN_FCD_DAY_DIFF_PER_7D NUMBER
    , TW_TWD_AMT_DIFF_PER_14D NUMBER
    , TW_TWD_CNT_DIFF_PER_14D NUMBER
    , TW_TWD_DAY_DIFF_PER_14D NUMBER
    , TW_FCD_AMT_DIFF_PER_14D NUMBER
    , TW_FCD_CNT_DIFF_PER_14D NUMBER
    , TW_FCD_DAY_DIFF_PER_14D NUMBER
    , FN_TWD_AMT_DIFF_PER_14D NUMBER
    , FN_TWD_CNT_DIFF_PER_14D NUMBER
    , FN_TWD_DAY_DIFF_PER_14D NUMBER
    , FN_FCD_AMT_DIFF_PER_14D NUMBER
    , FN_FCD_CNT_DIFF_PER_14D NUMBER
    , FN_FCD_DAY_DIFF_PER_14D NUMBER
    , TW_TWD_AMT_DIFF_PER_28D NUMBER
    , TW_TWD_CNT_DIFF_PER_28D NUMBER
    , TW_TWD_DAY_DIFF_PER_28D NUMBER
    , TW_FCD_AMT_DIFF_PER_28D NUMBER
    , TW_FCD_CNT_DIFF_PER_28D NUMBER
    , TW_FCD_DAY_DIFF_PER_28D NUMBER
    , FN_TWD_AMT_DIFF_PER_28D NUMBER
    , FN_TWD_CNT_DIFF_PER_28D NUMBER
    , FN_TWD_DAY_DIFF_PER_28D NUMBER
    , FN_FCD_AMT_DIFF_PER_28D NUMBER
    , FN_FCD_CNT_DIFF_PER_28D NUMBER
    , FN_FCD_DAY_DIFF_PER_28D NUMBER
    , TW_TWD_AMT_DIFF_PER_60D NUMBER
    , TW_TWD_CNT_DIFF_PER_60D NUMBER
    , TW_TWD_DAY_DIFF_PER_60D NUMBER
    , TW_FCD_AMT_DIFF_PER_60D NUMBER
    , TW_FCD_CNT_DIFF_PER_60D NUMBER
    , TW_FCD_DAY_DIFF_PER_60D NUMBER
    , FN_TWD_AMT_DIFF_PER_60D NUMBER
    , FN_TWD_CNT_DIFF_PER_60D NUMBER
    , FN_TWD_DAY_DIFF_PER_60D NUMBER
    , FN_FCD_AMT_DIFF_PER_60D NUMBER
    , FN_FCD_CNT_DIFF_PER_60D NUMBER
    , FN_FCD_DAY_DIFF_PER_60D NUMBER

    
   ) ;


DECLARE
    date1 NUMBER := 0; 
BEGIN

    EXECUTE IMMEDIATE 'TRUNCATE TABLE CDTX_FEATURES';
    
    WHILE date1 <= 394 LOOP
        INSERT INTO CDTX_FEATURES
        SELECT CUST_ID
        , date1
        --羆肂&羆Ω计
        , SUM(CASE WHEN DATEKEY <= DATE1 THEN AMT ELSE 0 END) ALL_AMT
        , COUNT(CASE WHEN DATEKEY <= DATE1 THEN DATEKEY ELSE NULL END) ALL_CNT
        , COUNT(DISTINCT CASE WHEN DATEKEY <= DATE1 THEN DATEKEY ELSE NULL END) ALL_DAY
        --程肂
        , MAX(CASE WHEN DATEKEY <= DATE1 THEN AMT ELSE 0 END) MAX_AMT
        
        --肂&Ω计
        , SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_1D
        , COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_1D
        , SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_1D
        , COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_1D
        , SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_1D
        , COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_1D
        , SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_1D
        , COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_1D
        
        --3
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_3D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_3D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_DAY_3D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_3D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_3D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_DAY_3D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_3D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_3D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_DAY_3D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_3D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_3D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_DAY_3D
        
        --7
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_7D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_7D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_DAY_7D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_7D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_7D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_DAY_7D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_7D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_7D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_DAY_7D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_7D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_7D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_DAY_7D
            
        --14
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_14D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_14D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_DAY_14D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_14D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_14D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_DAY_14D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_14D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_14D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_DAY_14D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_14D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_14D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_DAY_14D
          
        --28
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_28D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_28D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_DAY_28D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_28D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_28D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_DAY_28D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_28D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_28D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_DAY_28D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_28D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_28D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_DAY_28D
        
        --60
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_60D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_60D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_DAY_60D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_60D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_60D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_DAY_60D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_60D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_60D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_DAY_60D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_60D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_60D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_DAY_60D
        
        ---------------------------------------------------------------------------------------------------------------------------------------
        --肂畉Ω计畉
        --1
        , SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_1D
        , COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_DIFF_1D
        , COUNT(DISTINCT CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_DAY_DIFF_1D
        , SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_1D
        , COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_DIFF_1D
        , COUNT(DISTINCT CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_DAY_DIFF_1D
        , SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_1D
        , COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) -COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_DIFF_1D
        , COUNT(DISTINCT CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) -COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_DAY_DIFF_1D
        , SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_1D
        , COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_DIFF_1D
        , COUNT(DISTINCT CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_DAY_DIFF_1D
        
        --3
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_3D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_DIFF_3D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_DAY_DIFF_3D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_3D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_DIFF_3D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_DAY_DIFF_3D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_3D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_DIFF_3D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_DAY_DIFF_3D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) -SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_3D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_DIFF_3D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_DAY_DIFF_3D
        
        --7
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_7D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_DIFF_7D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_DAY_DIFF_7D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_7D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_DIFF_7D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_DAY_DIFF_7D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_7D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_DIFF_7D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_DAY_DIFF_7D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_7D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_DIFF_7D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_DAY_DIFF_7D
            
        --14
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_14D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_DIFF_14D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_DAY_DIFF_14D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_14D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_DIFF_14D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_DAY_DIFF_14D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_14D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_DIFF_14D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_DAY_DIFF_14D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_14D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_DIFF_14D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_DAY_DIFF_14D
          
        --28
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_28D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_DIFF_28D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_DAY_DIFF_28D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_28D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_DIFF_28D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_DAY_DIFF_28D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_28D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_DIFF_28D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_DAY_DIFF_28D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_28D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_DIFF_28D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_DAY_DIFF_28D
        
        --60
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) TW_TWD_AMT_DIFF_60D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_CNT_DIFF_60D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) TW_TWD_DAY_DIFF_60D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) TW_FCD_AMT_DIFF_60D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_CNT_DIFF_60D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) TW_FCD_DAY_DIFF_60D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) FN_TWD_AMT_DIFF_60D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_CNT_DIFF_60D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) FN_TWD_DAY_DIFF_60D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) FN_FCD_AMT_DIFF_60D
        , COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_CNT_DIFF_60D
        , COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) FN_FCD_DAY_DIFF_60D
        
        
        
        ---------------------------------------------------------------------------------------------------------------------------------------
        --肂畉ゑㄒΩ计畉ゑㄒ
        --1
        , -NVL((SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) TW_TWD_AMT_DIFF_PER_1D
        , -NVL((COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_CNT_DIFF_PER_1D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_DAY_DIFF_PER_1D
        , -NVL((SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) TW_FCD_AMT_DIFF_PER_1D
        , -NVL((COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_CNT_DIFF_PER_1D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY = DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_DAY_DIFF_PER_1D
        , -NVL((SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) FN_TWD_AMT_DIFF_PER_1D
        , -NVL((COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_CNT_DIFF_PER_1D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_DAY_DIFF_PER_1D
        , -NVL((SUM(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) FN_FCD_AMT_DIFF_PER_1D
        , -NVL((COUNT(CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_CNT_DIFF_PER_1D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY = DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY = DATE1-1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_DAY_DIFF_PER_1D
        
        --3
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) TW_TWD_AMT_DIFF_PER_3D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_CNT_DIFF_PER_3D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_DAY_DIFF_PER_3D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) TW_FCD_AMT_DIFF_PER_3D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_CNT_DIFF_PER_3D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_DAY_DIFF_PER_3D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) FN_TWD_AMT_DIFF_PER_3D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_CNT_DIFF_PER_3D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_DAY_DIFF_PER_3D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) FN_FCD_AMT_DIFF_PER_3D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_CNT_DIFF_PER_3D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-5 AND DATE1-3 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_DAY_DIFF_PER_3D
        
        --7
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) TW_TWD_AMT_DIFF_PER_7D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_CNT_DIFF_PER_7D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_DAY_DIFF_PER_7D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) TW_FCD_AMT_DIFF_PER_7D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_CNT_DIFF_PER_7D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_DAY_DIFF_PER_7D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) FN_TWD_AMT_DIFF_PER_7D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_CNT_DIFF_PER_7D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_DAY_DIFF_PER_7D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) FN_FCD_AMT_DIFF_PER_7D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_CNT_DIFF_PER_7D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1-7 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_DAY_DIFF_PER_7D
        
        
        
        --14
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) TW_TWD_AMT_DIFF_PER_14D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_CNT_DIFF_PER_14D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_DAY_DIFF_PER_14D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) TW_FCD_AMT_DIFF_PER_14D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_CNT_DIFF_PER_14D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_DAY_DIFF_PER_14D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) FN_TWD_AMT_DIFF_PER_14D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_CNT_DIFF_PER_14D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_DAY_DIFF_PER_14D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) FN_FCD_AMT_DIFF_PER_14D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_CNT_DIFF_PER_14D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1-14 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_DAY_DIFF_PER_14D
        
        --28
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) TW_TWD_AMT_DIFF_PER_28D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_CNT_DIFF_PER_28D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_DAY_DIFF_PER_28D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) TW_FCD_AMT_DIFF_PER_28D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_CNT_DIFF_PER_28D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_DAY_DIFF_PER_28D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) FN_TWD_AMT_DIFF_PER_28D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_CNT_DIFF_PER_28D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_DAY_DIFF_PER_28D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) FN_FCD_AMT_DIFF_PER_28D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_CNT_DIFF_PER_28D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-55 AND DATE1-28 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_DAY_DIFF_PER_28D
        
        --60
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) TW_TWD_AMT_DIFF_PER_60D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_CNT_DIFF_PER_60D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_TWD_DAY_DIFF_PER_60D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) TW_FCD_AMT_DIFF_PER_60D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_CNT_DIFF_PER_60D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY = 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) TW_FCD_DAY_DIFF_PER_60D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type = 47 THEN AMT ELSE 0 END), 0), 0) FN_TWD_AMT_DIFF_PER_60D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_CNT_DIFF_PER_60D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type = 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_TWD_DAY_DIFF_PER_60D
        , -NVL((SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END) - SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END))/NULLIF(SUM(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type != 47 THEN AMT ELSE 0 END), 0), 0) FN_FCD_AMT_DIFF_PER_60D
        , -NVL((COUNT(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_CNT_DIFF_PER_60D
        , -NVL((COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END) - COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN DATEKEY BETWEEN DATE1-119 AND DATE1-60 AND COUNTRY != 130 AND cur_type != 47 THEN DATEKEY ELSE NULL END), 0), 0) FN_FCD_DAY_DIFF_PER_60D
        
        
        FROM CDTX
        GROUP BY CUST_ID;
        
        
        COMMIT;
        DATE1 := DATE1+1;
    end loop; 
END;


