DROP TABLE 母體 PURGE;

CREATE TABLE 母體 AS
SELECT A.ALERT_KEY, A.CUST_ID, DATEKEY, RISK_RANK, OCCUPATION_CODE, TOTAL_ASSET, AGE
, C.SAR_FLAG
FROM (
    SELECT * FROM CUSTINFO
) A LEFT JOIN (
    SELECT * FROM public_alert_date
    UNION
    SELECT * FROM train_alert_key
) B ON A.ALERT_KEY = B.ALERT_KEY
LEFT JOIN (
    SELECT * FROM TRAIN_Y
) C ON B.ALERT_KEY = C.ALERT_KEY
;

SELECT * FROM 母體
;



DEFINE DATE1 = 28;


SELECT 
CUST_ID
, &DATE1 DATEKEY
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-1 AND &DATE1 THEN 1 ELSE 0 END) ALERT_TIMES_1D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-2 AND &DATE1 THEN 1 ELSE 0 END) ALERT_TIMES_3D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-6 AND &DATE1 THEN 1 ELSE 0 END) ALERT_TIMES_7D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-13 AND &DATE1 THEN 1 ELSE 0 END) "ALERT_TIMES-14D"
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-27 AND &DATE1 THEN 1 ELSE 0 END) ALERT_TIMES_28D
, SUM(CASE WHEN DATEKEY BETWEEN &DATE1-59 AND &DATE1 THEN 1 ELSE 0 END) ALERT_TIMES_28D
FROM 母體
GROUP BY CUST_ID
