drop table CUSTINFO_FEATURES PURGE;

CREATE TABLE CUSTINFO_FEATURES
   (	
    CUST_ID VARCHAR2(200 BYTE)
    , DATEKEY NUMBER
    , ALERT_TIMES_1D NUMBER
    , ALERT_TIMES_3D NUMBER
    , ALERT_TIMES_7D NUMBER
    , ALERT_TIMES_14D NUMBER
    , ALERT_TIMES_28D NUMBER
    , ALERT_TIMES_60D NUMBER
    
   ) ;


DECLARE
    date1 NUMBER := 0; 
BEGIN

    EXECUTE IMMEDIATE 'TRUNCATE TABLE CUSTINFO_FEATURES';
    
    WHILE date1 <= 394 LOOP
        INSERT INTO CUSTINFO_FEATURES
        
        SELECT 
        CUST_ID
        , DATE1 DATEKEY
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-1 AND DATE1 THEN 1 ELSE 0 END) ALERT_TIMES_1D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-2 AND DATE1 THEN 1 ELSE 0 END) ALERT_TIMES_3D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-6 AND DATE1 THEN 1 ELSE 0 END) ALERT_TIMES_7D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-13 AND DATE1 THEN 1 ELSE 0 END) ALERT_TIMES_14D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-27 AND DATE1 THEN 1 ELSE 0 END) ALERT_TIMES_28D
        , SUM(CASE WHEN DATEKEY BETWEEN DATE1-59 AND DATE1 THEN 1 ELSE 0 END) ALERT_TIMES_60D
        FROM ¥ÀÅé
        GROUP BY CUST_ID;

        
        COMMIT;
        DATE1 := DATE1+1;
    end loop; 
END;

