drop table REMIT_FEATURES PURGE;

CREATE TABLE REMIT_FEATURES
   (	
    CUST_ID VARCHAR2(200 BYTE)
 , DATEKEY NUMBER
, TRANS_0_AMT_1D NUMBER
, TRANS_0_CNT_1D NUMBER
, TRANS_0_DAY_1D NUMBER
, TRANS_0_AMT_DIFF_1D NUMBER
, TRANS_0_CNT_DIFF_1D NUMBER
, TRANS_0_DAY_DIFF_1D NUMBER
, TRANS_0_AMT_DIFF_PER_1D NUMBER
, TRANS_0_CNT_DIFF_PER_1D NUMBER
, TRANS_0_DAY_DIFF_PER_1D NUMBER
, TRANS_0_AMT_3D NUMBER
, TRANS_0_CNT_3D NUMBER
, TRANS_0_DAY_3D NUMBER
, TRANS_0_AMT_DIFF_3D NUMBER
, TRANS_0_CNT_DIFF_3D NUMBER
, TRANS_0_DAY_DIFF_3D NUMBER
, TRANS_0_AMT_DIFF_PER_3D NUMBER
, TRANS_0_CNT_DIFF_PER_3D NUMBER
, TRANS_0_DAY_DIFF_PER_3D NUMBER
, TRANS_0_AMT_7D NUMBER
, TRANS_0_CNT_7D NUMBER
, TRANS_0_DAY_7D NUMBER
, TRANS_0_AMT_DIFF_7D NUMBER
, TRANS_0_CNT_DIFF_7D NUMBER
, TRANS_0_DAY_DIFF_7D NUMBER
, TRANS_0_AMT_DIFF_PER_7D NUMBER
, TRANS_0_CNT_DIFF_PER_7D NUMBER
, TRANS_0_DAY_DIFF_PER_7D NUMBER
, TRANS_0_AMT_14D NUMBER
, TRANS_0_CNT_14D NUMBER
, TRANS_0_DAY_14D NUMBER
, TRANS_0_AMT_DIFF_14D NUMBER
, TRANS_0_CNT_DIFF_14D NUMBER
, TRANS_0_DAY_DIFF_14D NUMBER
, TRANS_0_AMT_DIFF_PER_14D NUMBER
, TRANS_0_CNT_DIFF_PER_14D NUMBER
, TRANS_0_DAY_DIFF_PER_14D NUMBER
, TRANS_0_AMT_28D NUMBER
, TRANS_0_CNT_28D NUMBER
, TRANS_0_DAY_28D NUMBER
, TRANS_0_AMT_DIFF_28D NUMBER
, TRANS_0_CNT_DIFF_28D NUMBER
, TRANS_0_DAY_DIFF_28D NUMBER
, TRANS_0_AMT_DIFF_PER_28D NUMBER
, TRANS_0_CNT_DIFF_PER_28D NUMBER
, TRANS_0_DAY_DIFF_PER_28D NUMBER
, TRANS_0_AMT_60D NUMBER
, TRANS_0_CNT_60D NUMBER
, TRANS_0_DAY_60D NUMBER
, TRANS_0_AMT_DIFF_60D NUMBER
, TRANS_0_CNT_DIFF_60D NUMBER
, TRANS_0_DAY_DIFF_60D NUMBER
, TRANS_0_AMT_DIFF_PER_60D NUMBER
, TRANS_0_CNT_DIFF_PER_60D NUMBER
, TRANS_0_DAY_DIFF_PER_60D NUMBER
, TRANS_1_AMT_1D NUMBER
, TRANS_1_CNT_1D NUMBER
, TRANS_1_DAY_1D NUMBER
, TRANS_1_AMT_DIFF_1D NUMBER
, TRANS_1_CNT_DIFF_1D NUMBER
, TRANS_1_DAY_DIFF_1D NUMBER
, TRANS_1_AMT_DIFF_PER_1D NUMBER
, TRANS_1_CNT_DIFF_PER_1D NUMBER
, TRANS_1_DAY_DIFF_PER_1D NUMBER
, TRANS_1_AMT_3D NUMBER
, TRANS_1_CNT_3D NUMBER
, TRANS_1_DAY_3D NUMBER
, TRANS_1_AMT_DIFF_3D NUMBER
, TRANS_1_CNT_DIFF_3D NUMBER
, TRANS_1_DAY_DIFF_3D NUMBER
, TRANS_1_AMT_DIFF_PER_3D NUMBER
, TRANS_1_CNT_DIFF_PER_3D NUMBER
, TRANS_1_DAY_DIFF_PER_3D NUMBER
, TRANS_1_AMT_7D NUMBER
, TRANS_1_CNT_7D NUMBER
, TRANS_1_DAY_7D NUMBER
, TRANS_1_AMT_DIFF_7D NUMBER
, TRANS_1_CNT_DIFF_7D NUMBER
, TRANS_1_DAY_DIFF_7D NUMBER
, TRANS_1_AMT_DIFF_PER_7D NUMBER
, TRANS_1_CNT_DIFF_PER_7D NUMBER
, TRANS_1_DAY_DIFF_PER_7D NUMBER
, TRANS_1_AMT_14D NUMBER
, TRANS_1_CNT_14D NUMBER
, TRANS_1_DAY_14D NUMBER
, TRANS_1_AMT_DIFF_14D NUMBER
, TRANS_1_CNT_DIFF_14D NUMBER
, TRANS_1_DAY_DIFF_14D NUMBER
, TRANS_1_AMT_DIFF_PER_14D NUMBER
, TRANS_1_CNT_DIFF_PER_14D NUMBER
, TRANS_1_DAY_DIFF_PER_14D NUMBER
, TRANS_1_AMT_28D NUMBER
, TRANS_1_CNT_28D NUMBER
, TRANS_1_DAY_28D NUMBER
, TRANS_1_AMT_DIFF_28D NUMBER
, TRANS_1_CNT_DIFF_28D NUMBER
, TRANS_1_DAY_DIFF_28D NUMBER
, TRANS_1_AMT_DIFF_PER_28D NUMBER
, TRANS_1_CNT_DIFF_PER_28D NUMBER
, TRANS_1_DAY_DIFF_PER_28D NUMBER
, TRANS_1_AMT_60D NUMBER
, TRANS_1_CNT_60D NUMBER
, TRANS_1_DAY_60D NUMBER
, TRANS_1_AMT_DIFF_60D NUMBER
, TRANS_1_CNT_DIFF_60D NUMBER
, TRANS_1_DAY_DIFF_60D NUMBER
, TRANS_1_AMT_DIFF_PER_60D NUMBER
, TRANS_1_CNT_DIFF_PER_60D NUMBER
, TRANS_1_DAY_DIFF_PER_60D NUMBER
, TRANS_2_AMT_1D NUMBER
, TRANS_2_CNT_1D NUMBER
, TRANS_2_DAY_1D NUMBER
, TRANS_2_AMT_DIFF_1D NUMBER
, TRANS_2_CNT_DIFF_1D NUMBER
, TRANS_2_DAY_DIFF_1D NUMBER
, TRANS_2_AMT_DIFF_PER_1D NUMBER
, TRANS_2_CNT_DIFF_PER_1D NUMBER
, TRANS_2_DAY_DIFF_PER_1D NUMBER
, TRANS_2_AMT_3D NUMBER
, TRANS_2_CNT_3D NUMBER
, TRANS_2_DAY_3D NUMBER
, TRANS_2_AMT_DIFF_3D NUMBER
, TRANS_2_CNT_DIFF_3D NUMBER
, TRANS_2_DAY_DIFF_3D NUMBER
, TRANS_2_AMT_DIFF_PER_3D NUMBER
, TRANS_2_CNT_DIFF_PER_3D NUMBER
, TRANS_2_DAY_DIFF_PER_3D NUMBER
, TRANS_2_AMT_7D NUMBER
, TRANS_2_CNT_7D NUMBER
, TRANS_2_DAY_7D NUMBER
, TRANS_2_AMT_DIFF_7D NUMBER
, TRANS_2_CNT_DIFF_7D NUMBER
, TRANS_2_DAY_DIFF_7D NUMBER
, TRANS_2_AMT_DIFF_PER_7D NUMBER
, TRANS_2_CNT_DIFF_PER_7D NUMBER
, TRANS_2_DAY_DIFF_PER_7D NUMBER
, TRANS_2_AMT_14D NUMBER
, TRANS_2_CNT_14D NUMBER
, TRANS_2_DAY_14D NUMBER
, TRANS_2_AMT_DIFF_14D NUMBER
, TRANS_2_CNT_DIFF_14D NUMBER
, TRANS_2_DAY_DIFF_14D NUMBER
, TRANS_2_AMT_DIFF_PER_14D NUMBER
, TRANS_2_CNT_DIFF_PER_14D NUMBER
, TRANS_2_DAY_DIFF_PER_14D NUMBER
, TRANS_2_AMT_28D NUMBER
, TRANS_2_CNT_28D NUMBER
, TRANS_2_DAY_28D NUMBER
, TRANS_2_AMT_DIFF_28D NUMBER
, TRANS_2_CNT_DIFF_28D NUMBER
, TRANS_2_DAY_DIFF_28D NUMBER
, TRANS_2_AMT_DIFF_PER_28D NUMBER
, TRANS_2_CNT_DIFF_PER_28D NUMBER
, TRANS_2_DAY_DIFF_PER_28D NUMBER
, TRANS_2_AMT_60D NUMBER
, TRANS_2_CNT_60D NUMBER
, TRANS_2_DAY_60D NUMBER
, TRANS_2_AMT_DIFF_60D NUMBER
, TRANS_2_CNT_DIFF_60D NUMBER
, TRANS_2_DAY_DIFF_60D NUMBER
, TRANS_2_AMT_DIFF_PER_60D NUMBER
, TRANS_2_CNT_DIFF_PER_60D NUMBER
, TRANS_2_DAY_DIFF_PER_60D NUMBER
, TRANS_3_AMT_1D NUMBER
, TRANS_3_CNT_1D NUMBER
, TRANS_3_DAY_1D NUMBER
, TRANS_3_AMT_DIFF_1D NUMBER
, TRANS_3_CNT_DIFF_1D NUMBER
, TRANS_3_DAY_DIFF_1D NUMBER
, TRANS_3_AMT_DIFF_PER_1D NUMBER
, TRANS_3_CNT_DIFF_PER_1D NUMBER
, TRANS_3_DAY_DIFF_PER_1D NUMBER
, TRANS_3_AMT_3D NUMBER
, TRANS_3_CNT_3D NUMBER
, TRANS_3_DAY_3D NUMBER
, TRANS_3_AMT_DIFF_3D NUMBER
, TRANS_3_CNT_DIFF_3D NUMBER
, TRANS_3_DAY_DIFF_3D NUMBER
, TRANS_3_AMT_DIFF_PER_3D NUMBER
, TRANS_3_CNT_DIFF_PER_3D NUMBER
, TRANS_3_DAY_DIFF_PER_3D NUMBER
, TRANS_3_AMT_7D NUMBER
, TRANS_3_CNT_7D NUMBER
, TRANS_3_DAY_7D NUMBER
, TRANS_3_AMT_DIFF_7D NUMBER
, TRANS_3_CNT_DIFF_7D NUMBER
, TRANS_3_DAY_DIFF_7D NUMBER
, TRANS_3_AMT_DIFF_PER_7D NUMBER
, TRANS_3_CNT_DIFF_PER_7D NUMBER
, TRANS_3_DAY_DIFF_PER_7D NUMBER
, TRANS_3_AMT_14D NUMBER
, TRANS_3_CNT_14D NUMBER
, TRANS_3_DAY_14D NUMBER
, TRANS_3_AMT_DIFF_14D NUMBER
, TRANS_3_CNT_DIFF_14D NUMBER
, TRANS_3_DAY_DIFF_14D NUMBER
, TRANS_3_AMT_DIFF_PER_14D NUMBER
, TRANS_3_CNT_DIFF_PER_14D NUMBER
, TRANS_3_DAY_DIFF_PER_14D NUMBER
, TRANS_3_AMT_28D NUMBER
, TRANS_3_CNT_28D NUMBER
, TRANS_3_DAY_28D NUMBER
, TRANS_3_AMT_DIFF_28D NUMBER
, TRANS_3_CNT_DIFF_28D NUMBER
, TRANS_3_DAY_DIFF_28D NUMBER
, TRANS_3_AMT_DIFF_PER_28D NUMBER
, TRANS_3_CNT_DIFF_PER_28D NUMBER
, TRANS_3_DAY_DIFF_PER_28D NUMBER
, TRANS_3_AMT_60D NUMBER
, TRANS_3_CNT_60D NUMBER
, TRANS_3_DAY_60D NUMBER
, TRANS_3_AMT_DIFF_60D NUMBER
, TRANS_3_CNT_DIFF_60D NUMBER
, TRANS_3_DAY_DIFF_60D NUMBER
, TRANS_3_AMT_DIFF_PER_60D NUMBER
, TRANS_3_CNT_DIFF_PER_60D NUMBER
, TRANS_3_DAY_DIFF_PER_60D NUMBER
, TRANS_4_AMT_1D NUMBER
, TRANS_4_CNT_1D NUMBER
, TRANS_4_DAY_1D NUMBER
, TRANS_4_AMT_DIFF_1D NUMBER
, TRANS_4_CNT_DIFF_1D NUMBER
, TRANS_4_DAY_DIFF_1D NUMBER
, TRANS_4_AMT_DIFF_PER_1D NUMBER
, TRANS_4_CNT_DIFF_PER_1D NUMBER
, TRANS_4_DAY_DIFF_PER_1D NUMBER
, TRANS_4_AMT_3D NUMBER
, TRANS_4_CNT_3D NUMBER
, TRANS_4_DAY_3D NUMBER
, TRANS_4_AMT_DIFF_3D NUMBER
, TRANS_4_CNT_DIFF_3D NUMBER
, TRANS_4_DAY_DIFF_3D NUMBER
, TRANS_4_AMT_DIFF_PER_3D NUMBER
, TRANS_4_CNT_DIFF_PER_3D NUMBER
, TRANS_4_DAY_DIFF_PER_3D NUMBER
, TRANS_4_AMT_7D NUMBER
, TRANS_4_CNT_7D NUMBER
, TRANS_4_DAY_7D NUMBER
, TRANS_4_AMT_DIFF_7D NUMBER
, TRANS_4_CNT_DIFF_7D NUMBER
, TRANS_4_DAY_DIFF_7D NUMBER
, TRANS_4_AMT_DIFF_PER_7D NUMBER
, TRANS_4_CNT_DIFF_PER_7D NUMBER
, TRANS_4_DAY_DIFF_PER_7D NUMBER
, TRANS_4_AMT_14D NUMBER
, TRANS_4_CNT_14D NUMBER
, TRANS_4_DAY_14D NUMBER
, TRANS_4_AMT_DIFF_14D NUMBER
, TRANS_4_CNT_DIFF_14D NUMBER
, TRANS_4_DAY_DIFF_14D NUMBER
, TRANS_4_AMT_DIFF_PER_14D NUMBER
, TRANS_4_CNT_DIFF_PER_14D NUMBER
, TRANS_4_DAY_DIFF_PER_14D NUMBER
, TRANS_4_AMT_28D NUMBER
, TRANS_4_CNT_28D NUMBER
, TRANS_4_DAY_28D NUMBER
, TRANS_4_AMT_DIFF_28D NUMBER
, TRANS_4_CNT_DIFF_28D NUMBER
, TRANS_4_DAY_DIFF_28D NUMBER
, TRANS_4_AMT_DIFF_PER_28D NUMBER
, TRANS_4_CNT_DIFF_PER_28D NUMBER
, TRANS_4_DAY_DIFF_PER_28D NUMBER
, TRANS_4_AMT_60D NUMBER
, TRANS_4_CNT_60D NUMBER
, TRANS_4_DAY_60D NUMBER
, TRANS_4_AMT_DIFF_60D NUMBER
, TRANS_4_CNT_DIFF_60D NUMBER
, TRANS_4_DAY_DIFF_60D NUMBER
, TRANS_4_AMT_DIFF_PER_60D NUMBER
, TRANS_4_CNT_DIFF_PER_60D NUMBER
, TRANS_4_DAY_DIFF_PER_60D NUMBER

   ) ;


DECLARE
    date1 NUMBER := 0; 
BEGIN

    EXECUTE IMMEDIATE 'TRUNCATE TABLE REMIT_FEATURES';
    
    WHILE date1 <= 394 LOOP
        INSERT INTO REMIT_FEATURES
                           
    SELECT
    CUST_ID
    , DATE1 DATEKEY
    ---------------------------------------------------------------------------------------------------------------------------------------
    --TRANS_NO =  0
    --1 
    , SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_1D
    , COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_1D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_1D
    , SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_DIFF_1D
    , COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_DIFF_1D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_DIFF_1D
    , -NVL((SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_0_AMT_DIFF_PER_1D
    , -NVL((COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_CNT_DIFF_PER_1D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_DAY_DIFF_PER_1D
    
    --3 
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_3D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_3D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_3D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_DIFF_3D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_DIFF_3D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_DIFF_3D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_0_AMT_DIFF_PER_3D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_CNT_DIFF_PER_3D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_DAY_DIFF_PER_3D
    
    --7
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_7D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_7D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_7D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_DIFF_7D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_DIFF_7D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_DIFF_7D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_0_AMT_DIFF_PER_7D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_CNT_DIFF_PER_7D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_DAY_DIFF_PER_7D
    
    --14
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_14D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_14D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_14D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_DIFF_14D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_DIFF_14D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_DIFF_14D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_0_AMT_DIFF_PER_14D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_CNT_DIFF_PER_14D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_DAY_DIFF_PER_14D
    
    
    
    --28
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_28D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_28D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_28D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_DIFF_28D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_DIFF_28D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_DIFF_28D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_0_AMT_DIFF_PER_28D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_CNT_DIFF_PER_28D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_DAY_DIFF_PER_28D
    
    
    --60
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_60D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_60D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_60D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_0_AMT_DIFF_60D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_CNT_DIFF_60D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) TRANS_0_DAY_DIFF_60D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '0' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_0_AMT_DIFF_PER_60D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_CNT_DIFF_PER_60D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '0' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_0_DAY_DIFF_PER_60D
    
    
    
    ---------------------------------------------------------------------------------------------------------------------------------------
    --TRANS_NO = '1'
    --1 
    , SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_1D
    , COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_1D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_1D
    , SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_DIFF_1D
    , COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_DIFF_1D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_DIFF_1D
    , -NVL((SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_1_AMT_DIFF_PER_1D
    , -NVL((COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_CNT_DIFF_PER_1D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_DAY_DIFF_PER_1D
    
    --3 
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_3D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_3D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_3D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_DIFF_3D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_DIFF_3D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_DIFF_3D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_1_AMT_DIFF_PER_3D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_CNT_DIFF_PER_3D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_DAY_DIFF_PER_3D
    
    --7
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_7D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_7D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_7D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_DIFF_7D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_DIFF_7D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_DIFF_7D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_1_AMT_DIFF_PER_7D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_CNT_DIFF_PER_7D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_DAY_DIFF_PER_7D
    
    --14
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_14D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_14D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_14D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_DIFF_14D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_DIFF_14D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_DIFF_14D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_1_AMT_DIFF_PER_14D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_CNT_DIFF_PER_14D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_DAY_DIFF_PER_14D
    
    
    
    --28
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_28D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_28D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_28D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_DIFF_28D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_DIFF_28D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_DIFF_28D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_1_AMT_DIFF_PER_28D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_CNT_DIFF_PER_28D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_DAY_DIFF_PER_28D
    
    
    --60
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_60D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_60D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_60D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_1_AMT_DIFF_60D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_CNT_DIFF_60D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) TRANS_1_DAY_DIFF_60D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '1' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_1_AMT_DIFF_PER_60D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_CNT_DIFF_PER_60D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '1' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_1_DAY_DIFF_PER_60D
    
    
    
    ---------------------------------------------------------------------------------------------------------------------------------------
    --TRANS_NO = '2'
    --1 
    , SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_1D
    , COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_1D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_1D
    , SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_DIFF_1D
    , COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_DIFF_1D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_DIFF_1D
    , -NVL((SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_2_AMT_DIFF_PER_1D
    , -NVL((COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_CNT_DIFF_PER_1D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_DAY_DIFF_PER_1D
    
    --3 
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_3D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_3D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_3D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_DIFF_3D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_DIFF_3D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_DIFF_3D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_2_AMT_DIFF_PER_3D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_CNT_DIFF_PER_3D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_DAY_DIFF_PER_3D
    
    --7
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_7D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_7D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_7D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_DIFF_7D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_DIFF_7D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_DIFF_7D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_2_AMT_DIFF_PER_7D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_CNT_DIFF_PER_7D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_DAY_DIFF_PER_7D
    
    --14
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_14D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_14D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_14D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_DIFF_14D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_DIFF_14D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_DIFF_14D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_2_AMT_DIFF_PER_14D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_CNT_DIFF_PER_14D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_DAY_DIFF_PER_14D
    
    
    
    --28
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_28D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_28D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_28D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_DIFF_28D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_DIFF_28D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_DIFF_28D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_2_AMT_DIFF_PER_28D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_CNT_DIFF_PER_28D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_DAY_DIFF_PER_28D
    
    
    --60
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_60D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_60D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_60D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_2_AMT_DIFF_60D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_CNT_DIFF_60D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) TRANS_2_DAY_DIFF_60D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '2' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_2_AMT_DIFF_PER_60D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_CNT_DIFF_PER_60D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '2' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_2_DAY_DIFF_PER_60D
    
    
    
    ---------------------------------------------------------------------------------------------------------------------------------------
    --TRANS_NO = '3'
    --1 
    , SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_1D
    , COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_1D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_1D
    , SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_DIFF_1D
    , COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_DIFF_1D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_DIFF_1D
    , -NVL((SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_3_AMT_DIFF_PER_1D
    , -NVL((COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_CNT_DIFF_PER_1D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_DAY_DIFF_PER_1D
    
    --3 
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_3D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_3D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_3D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_DIFF_3D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_DIFF_3D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_DIFF_3D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_3_AMT_DIFF_PER_3D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_CNT_DIFF_PER_3D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_DAY_DIFF_PER_3D
    
    --7
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_7D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_7D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_7D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_DIFF_7D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_DIFF_7D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_DIFF_7D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_3_AMT_DIFF_PER_7D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_CNT_DIFF_PER_7D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_DAY_DIFF_PER_7D
    
    --14
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_14D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_14D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_14D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_DIFF_14D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_DIFF_14D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_DIFF_14D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_3_AMT_DIFF_PER_14D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_CNT_DIFF_PER_14D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_DAY_DIFF_PER_14D
    
    
    
    --28
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_28D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_28D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_28D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_DIFF_28D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_DIFF_28D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_DIFF_28D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_3_AMT_DIFF_PER_28D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_CNT_DIFF_PER_28D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_DAY_DIFF_PER_28D
    
    
    --60
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_60D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_60D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_60D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_3_AMT_DIFF_60D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_CNT_DIFF_60D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) TRANS_3_DAY_DIFF_60D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '3' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_3_AMT_DIFF_PER_60D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_CNT_DIFF_PER_60D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '3' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_3_DAY_DIFF_PER_60D
    
    
    
    ---------------------------------------------------------------------------------------------------------------------------------------
    --TRANS_NO = '4'
    --1 
    , SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_1D
    , COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_1D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_1D
    , SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_DIFF_1D
    , COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_DIFF_1D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_DIFF_1D
    , -NVL((SUM(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_4_AMT_DIFF_PER_1D
    , -NVL((COUNT(CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_CNT_DIFF_PER_1D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE = DATE1-1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_DAY_DIFF_PER_1D
    
    --3 
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_3D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_3D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_3D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_DIFF_3D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_DIFF_3D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_DIFF_3D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_4_AMT_DIFF_PER_3D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_CNT_DIFF_PER_3D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-2 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-5 AND DATE1-3 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_DAY_DIFF_PER_3D
    
    --7
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_7D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_7D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_7D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_DIFF_7D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_DIFF_7D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_DIFF_7D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_4_AMT_DIFF_PER_7D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_CNT_DIFF_PER_7D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-6 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1-7 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_DAY_DIFF_PER_7D
    
    --14
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_14D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_14D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_14D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_DIFF_14D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_DIFF_14D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_DIFF_14D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_4_AMT_DIFF_PER_14D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_CNT_DIFF_PER_14D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-13 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1-14 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_DAY_DIFF_PER_14D
    
    
    
    --28
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_28D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_28D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_28D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_DIFF_28D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_DIFF_28D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_DIFF_28D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_4_AMT_DIFF_PER_28D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_CNT_DIFF_PER_28D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-27 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-55 AND DATE1-28 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_DAY_DIFF_PER_28D
    
    
    --60
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_60D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_60D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_60D
    , SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) TRANS_4_AMT_DIFF_60D
    , COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_CNT_DIFF_60D
    , COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) TRANS_4_DAY_DIFF_60D
    , -NVL((SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END) - SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END))/NULLIF(SUM(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '4' THEN TRADE_AMOUNT_USD ELSE 0 END), 0), 0) TRANS_4_AMT_DIFF_PER_60D
    , -NVL((COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_CNT_DIFF_PER_60D
    , -NVL((COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-59 AND DATE1 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END) - COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END))/NULLIF(COUNT(DISTINCT CASE WHEN TRANS_DATE BETWEEN DATE1-119 AND DATE1-60 AND TRANS_NO = '4' THEN TRANS_DATE ELSE NULL END), 0), 0) TRANS_4_DAY_DIFF_PER_60D
    
    
    
    FROM REMIT
    GROUP BY CUST_ID;
        
        COMMIT;
        DATE1 := DATE1+1;
    end loop; 
END;
  
  